### ISSUE TITLE
Failure when building project

### ISSUE THREAD

**Issue by alexruiz** [kageiit/android-studio-gradle-test#1]
Adam (from Gradle, Inc.) mentioned this failure in an email thread: https://e.grdev.net/s/6w77teqn37ujm

Gautam, I haven't had the chance to look at this yet, but I thought it would be worth rising this issue on the meantime. Thanks! :-)

**Comment by kageiit** [comment]
a bunch of project fixes were made recently. Please try on the current master. The issue you mentioned should be resolved

**Comment by kageiit** [comment]
Feel free to re-open if you still see any issues
